env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  timeout_in: 120m
  freebsd_instance:
    matrix:
      image_family: freebsd-12-2
      image_family: freebsd-11-4
    cpu: 8
    memory: 16G
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg install -y poudriere rsync
  script:
    - ./porttest.sh
  env:
    matrix:
      PORT_OPTION_SET: ""
      PORT_OPTION_SET: "jlall"
      PORT_OPTION_SET: "openblas"
      PORT_OPTION_SET: "syslibm"
